version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - /volume1/docker/uvdeskdb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_ROOT_PASSWORD: abbasi94
      MYSQL_USER: uvdesk
      MYSQL_PASSWORD: abbasi94
  uvdesk:
    image: nuttcorp/uvdesk:latest
    depends_on:
      - db
    tty: true
    environment:
        MYSQL_USER: uvdesk
        MYSQL_PASSWORD: abbasi94
        MYSQL_ROOT_PASSWORD: abbasi94
        MYSQL_DATABASE: uvdesk
    ports:
        - 88:80
